# Generated by Django 4.2.6 on 2023-12-04 05:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='rented_date',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='returned',
        ),
        migrations.AddField(
            model_name='fine',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fine',
            name='rent',
            field=models.OneToOneField(default=9, on_delete=django.db.models.deletion.CASCADE, to='myapp.rent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='rent_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='rent',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
