# Generated by Django 4.2.6 on 2023-12-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
